name: Linux Server Power Control

on:
  workflow_dispatch:
    inputs:
      server:
        description: "Select Server"
        required: true
        type: choice
        options:
          - linux1

      action:
        description: "Select Action"
        required: true
        type: choice
        options:
          - status
          - restart
          - stop

jobs:
  control:
    runs-on: ubuntu-latest

    steps:
      - name: Execute on Linux Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.LINUX1_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Server: ${{ github.event.inputs.server }}"
            echo "Action: ${{ github.event.inputs.action }}"

            if [ "${{ github.event.inputs.action }}" = "status" ]; then
              hostname
              uptime

            elif [ "${{ github.event.inputs.action }}" = "restart" ]; then
              sudo reboot

            elif [ "${{ github.event.inputs.action }}" = "stop" ]; then
              sudo shutdown -h now

            fi